/**
 * scribe.js — Report Formatter & Persistence Agent
 *
 * Interface:
 *   scribe.write(ctx, plan) → Promise<string>
 *
 * Returns a formatted report string (Markdown or JSON) and optionally
 * persists it to disk as `upgrade-report.md` / `upgrade-report.json`
 * inside ctx.targetPath.
 *
 * ctx:  { targetPath, format: 'markdown' | 'json', dryRun, verbose }
 * plan: UpgradePlan from planner.buildPlan()
 *
 * Output shape (Markdown):
 *   # UpgradePilot Report — <project>
 *   Generated: <ISO date>
 *   Risk Score: <n>/100
 *
 *   ## Step 1 — <package>
 *   ...
 *
 * Output shape (JSON):
 *   The full UpgradePlan object, pretty-printed.
 */

import fs   from 'fs';
import path from 'path';

// ─── Markdown renderer ────────────────────────────────────────────────────────
function toMarkdown(plan) {
  const lines = [
    `# UpgradePilot Upgrade Report`,
    ``,
    `**Project:** \`${plan.projectPath}\`  `,
    `**Generated:** ${plan.createdAt}  `,
    `**Aggregate Risk Score:** ${plan.riskScore}/100  `,
    `**Summary:** ${plan.summary}`,
    ``,
    `---`,
    ``,
  ];

  if (plan.steps.length === 0) {
    lines.push('> ✅ Nothing to upgrade — all dependencies are up-to-date.');
  }

  for (const step of plan.steps) {
    lines.push(
      `## Step ${step.order} — \`${step.package}\``,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| Current version | \`${step.fromVersion}\` |`,
      `| Target version  | \`${step.toVersion}\`  |`,
      `| Risk level      | **${step.risk}** (${step.riskScore}/100) |`,
      ``,
    );

    if (step.migrationSteps.length) {
      lines.push('### Migration steps', '');
      step.migrationSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      lines.push('');
    }

    if (step.references.length) {
      lines.push('### References', '');
      step.references.forEach(r => lines.push(`- <${r}>`));
      lines.push('');
    }

    lines.push('---', '');
  }

  lines.push('*Generated by [UpgradePilot](https://github.com/upgradepilot/upgradepilot)*');
  return lines.join('\n');
}

// ─── JSON renderer ────────────────────────────────────────────────────────────
function toJson(plan) {
  return JSON.stringify(plan, null, 2);
}

async function write(ctx, plan) {
  const fmt    = ctx.format === 'json' ? 'json' : 'markdown';
  const output = fmt === 'json' ? toJson(plan) : toMarkdown(plan);

  if (!ctx.dryRun) {
    const ext      = fmt === 'json' ? '.json' : '.md';
    const outFile  = path.join(ctx.targetPath, `upgrade-report${ext}`);
    fs.writeFileSync(outFile, output, 'utf8');
    if (ctx.verbose) {
      console.log(`[scribe] Report written to ${outFile}`);
    }
  }

  return output;
}

export const scribe = { write };
