/**
 * scribe.js — Report Formatter & Persistence Agent
 *
 * Interface:
 *   scribe.write(ctx, plan) → Promise<string>
 *
 * Returns a formatted report string (Markdown or JSON) and optionally
 * persists it to disk as `upgrade-report.md` / `upgrade-report.json`
 * inside ctx.targetPath.
 *
 * ctx:  { targetPath, format: 'markdown' | 'json', dryRun, verbose }
 * plan: UpgradePlan from planner.buildPlan()
 *
 * Output shape (Markdown):
 *   # UpgradePilot Report — <project>
 *   Generated: <ISO date>
 *   Risk Score: <n>/100
 *
 *   ## Step 1 — <package>
 *   ...
 *
 * Output shape (JSON):
 *   The full UpgradePlan object, pretty-printed.
 */

import fs   from 'fs';
import path from 'path';

// ─── Markdown renderer ────────────────────────────────────────────────────────
function toMarkdown(plan) {
  // Support both planner output shape (plan.packages) and legacy shape (plan.steps)
  const packages   = plan.packages || plan.steps || [];
  const riskScore  = plan.totalRiskScore ?? plan.riskScore ?? 0;
  const ecosystem  = plan.ecosystem ? ` (${plan.ecosystem})` : '';

  const lines = [
    `# UpgradePilot Upgrade Report${ecosystem}`,
    ``,
    `**Project:** \`${plan.projectPath}\`  `,
    `**Generated:** ${plan.createdAt}  `,
    `**Aggregate Risk Score:** ${riskScore}/100  `,
    `**Summary:** ${plan.summary}`,
    ``,
    `---`,
    ``,
  ];

  if (packages.length === 0) {
    lines.push('> ✅ Nothing to upgrade — no breaking changes detected.');
    lines.push('');
  }

  for (const pkg of packages) {
    const riskEmoji = pkg.risk === 'high' ? '🔴' : pkg.risk === 'medium' ? '🟡' : '🟢';
    lines.push(
      `## Step ${pkg.order} — \`${pkg.package}\` ${riskEmoji}`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| Current version | \`${pkg.from ?? pkg.fromVersion ?? '?'}\` |`,
      `| Target version  | \`${pkg.to ?? pkg.toVersion ?? '?'}\`   |`,
      `| Risk level      | **${pkg.risk}** (${pkg.riskScore}/100) |`,
      `| Affected files  | ${pkg.affectedFileCount ?? 0} |`,
      `| Manual effort   | ${pkg.estimatedManualMinutes ?? '?'} min |`,
      `| Pilot effort    | ${pkg.estimatedPilotMinutes ?? '?'} min |`,
      ``,
    );

    // Rule-level actions
    const steps = pkg.steps || pkg.migrationSteps || [];
    if (steps.length) {
      lines.push('### Migration steps', '');
      if (typeof steps[0] === 'string') {
        steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      } else {
        steps.filter(s => s.occurrences > 0).forEach((s, i) =>
          lines.push(`${i + 1}. **[${s.ruleId}]** ${s.action}`)
        );
      }
      lines.push('');
    }

    const refs = pkg.references || [];
    if (refs.length) {
      lines.push('### References', '');
      refs.forEach(r => lines.push(`- <${r}>`));
      lines.push('');
    }

    lines.push(`> **Rollback:** ${pkg.rollbackNote || 'Revert changes via git.'}`, '');
    lines.push('---', '');
  }

  lines.push('*Generated by [UpgradePilot](https://github.com/upgradepilot/upgradepilot)*');
  return lines.join('\n');
}

// ─── JSON renderer ────────────────────────────────────────────────────────────
function toJson(plan) {
  return JSON.stringify(plan, null, 2);
}

async function write(ctx, plan) {
  const fmt    = ctx.format === 'json' ? 'json' : 'markdown';
  const output = fmt === 'json' ? toJson(plan) : toMarkdown(plan);

  if (!ctx.dryRun) {
    const ext      = fmt === 'json' ? '.json' : '.md';
    const outFile  = path.join(ctx.targetPath, `upgrade-report${ext}`);
    fs.writeFileSync(outFile, output, 'utf8');
    if (ctx.verbose) {
      console.log(`[scribe] Report written to ${outFile}`);
    }
  }

  return output;
}

export const scribe = { write };
